---
- name: Import mumble tasks
  ansible.builtin.import_tasks: mumble.yml

- name: Import mumble-web tasks
  ansible.builtin.import_tasks: mumble-web.yml
  when: mumble_web
  tags: mumble-web

- name: Import goss tasks
  ansible.builtin.import_tasks: goss.yml
  tags:
    - goss
