---
- name: Import mumble tasks
  ansible.builtin.import_tasks: mumble.yml

- name: Import mumble-web tasks
  ansible.builtin.import_tasks: mumble-web.yml
  when: mumble_web
  tags: mumble-web

- name: Import monitoring tasks
  ansible.builtin.import_tasks: monitoring.yml
  when: murmur_monitoring_monit_enabled or murmur_monitoring_munin_enabled

- name: Import goss tasks
  ansible.builtin.import_tasks: goss.yml
  tags:
    - goss
