---
- name: Install dependencies to make munin plugin work
  ansible.builtin.apt:
    pkg: "{{ murmur_monitoring_munin_packages }}"

# plugin taken from https://github.com/Natenom/munin-plugins/issues/10
- name: Copy munin plugin
  ansible.builtin.copy:
    src: murmur-munin.py
    dest: /usr/local/share/
    owner: root
    group: root
    mode: "0755"

- name: Ensure mumble plugins are present
  ansible.builtin.file:
    src: "/usr/local/share/murmur-munin.py"
    dest: "/etc/munin/plugins/mumble"
    state: link
  when: murmur_monitoring_munin_enabled
  notify: Restart munin-node

- name: Ensure monit service config is latest
  ansible.builtin.copy:
    src: "monit/conf.d/mumble-server"
    dest: "/etc/monit/conf.d/mumble-server"
    owner: root
    group: root
    mode: "0600"
  notify: Restart monit
  when: murmur_monitoring_monit_enabled
