---
- name: Install dependencies
  ansible.builtin.apt:
    pkg: websockify

- name: Install mumble-web
  community.general.npm:
    name: mumble-web
    global: True

- name: Copy mumble-web unit file
  ansible.builtin.template:
    src: mumble-web.service.j2
    dest: /etc/systemd/system/mumble-web.service
    owner: root
    group: root
    mode: "0644"
  register: servicefile
  notify:
    - Set Python capabilities
    - Restart mumble-web

- name: Configure mumble-web
  ansible.builtin.template:
    src: config.local.js.j2
    dest: "{{ mumble_web_path }}/dist/config.local.js"
    owner: root
    group: root
    mode: "0644"

- name: Wnable and start mumble-web
  ansible.builtin.systemd:
    name: mumble-web
    daemon-reload: yes
    enabled: True
    state: started
