---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: bookworm64
    box: debian/bookworm64
  - name: trixie64
    box: debian/trixie64
provisioner:
  name: ansible
  become: True
lint: yamllint .
